blog/urls.py
from django.urls import path, include
from blog.views import single_view, home_view, search_view
from blog.feeds import LatestBlogs

app_name = "blog"

urlpatterns = [
    path("", home_view, name="home"),
    path("post-<slug:slug>-<int:post_id>", single_view, name="single"),
    path("categories/<str:category_type>", home_view, name="categories"),
    path("tags/<str:tag_name>", home_view, name="tags"),
    path("categories/", home_view),
    path("writer/<str:author_username>", home_view, name="author"),
    path("rss/feed/", LatestBlogs()),
    path("search/", search_view, name="search")
    # path("name/<str:name>/email/<str:email>/year/<int:year>", test_view, name="test"),
    # path("post-<slug:slug>-<int:post_id>", post_view, name="details")
]

home/urls.py
from django.urls import path, include
from home.views import home_view, about_view, contact_view

app_name = "home"

urlpatterns = [
    path("", home_view, name="index"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact")
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import HomeStaticViewSitemap
from contact.sitemaps import ContactStaticViewSitemap
from about.sitemaps import AboutStaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {"home": HomeStaticViewSitemap,
            "contact": ContactStaticViewSitemap,
            "about": AboutStaticViewSitemap,
            "blog": BlogSitemap}

from robots.views import R


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("website/", include("website.urls"), name="web"),
    path("about/", include("about.urls")),
    path("contact/", include("contact.urls")),
    path("elements/", include("elements.urls")),
    path("blog/", include("blog.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("user_management.urls")),
    path("accounts/", include("allauth.urls")),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()
urlpatterns += [path('captcha/', include('captcha.urls')),]

home/models.py
from django.db import models


class NewsLetter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

home/forms.py
from django.forms import ModelForm
from home.models import NewsLetter


class NewsLetterForm(ModelForm):
    class Meta:
        model = NewsLetter
        fields = "__all__"

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from home.forms import NewsLetterForm


def home_view(request):
    if request.method == "POST":
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")

    return render(request, "travelista/home/index.html")

templates/travelista/home/add_lastest_tags.html
<div class="row">
    <div class="active-recent-blog-carusel">
        {% for post in posts %}
        <div class="single-recent-blog-post item">
            <div class="thumb">
                <img class="img-fluid" src="{{ post.image.url }}" alt="">
            </div>
            <div class="details">
                <div class="tags">
                    <ul>
                        {% for category in post.category.all %}
                        <li>
                            <a href="{% url 'blog:categories' category.category_type %}">{{category.category_type}}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <a href="{% url 'blog:single' slug=post.slug post_id=post.id %}">
                    <h4 class="title">{{post.title}}</h4>
                </a>
                <p>
                    {{post.title}}
                </p>
                <h6 class="date">{{post.published_date|date:"D M Y"}}</h6>
            </div>
        </div>
        {% endfor %}
    </div>
</div>