about/urls.py
from django.urls import path, include
from about.views import main_about_page

app_name = "about"

urlpatterns = [
    path("", main_about_page, name="about"),
]

blog/urls.py
from django.urls import path, include
from blog.views import single_view, home_view, search_view
from blog.feeds import LatestBlogs

app_name = "blog"

urlpatterns = [
    path("", home_view, name="home"),
    path("post-<slug:slug>-<int:post_id>", single_view, name="single"),
    path("categories/<str:category_type>", home_view, name="categories"),
    path("tags/<str:tag_name>", home_view, name="tags"),
    path("categories/", home_view),
    path("writer/<str:author_username>", home_view, name="author"),
    path("rss/feed/", LatestBlogs()),
    path("search/", search_view, name="search")
    # path("name/<str:name>/email/<str:email>/year/<int:year>", test_view, name="test"),
    # path("post-<slug:slug>-<int:post_id>", post_view, name="details")
]

contact/urls.py
from django.contrib import admin
from django.urls import path, include
from contact.views import contact_main_page

app_name = "contact"


urlpatterns = [
    path("", contact_main_page, name="contact"),
]

home/urls.py
from django.urls import path, include
from home.views import home_view, about_view, contact_view

app_name = "home"

urlpatterns = [
    path("", home_view, name="index"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact")
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import HomeStaticViewSitemap
from contact.sitemaps import ContactStaticViewSitemap
from about.sitemaps import AboutStaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {"home": HomeStaticViewSitemap,
            "contact": ContactStaticViewSitemap,
            "about": AboutStaticViewSitemap,
            "blog": BlogSitemap}

from robots.views import R


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("website/", include("website.urls"), name="web"),
    path("about/", include("about.urls")),
    path("contact/", include("contact.urls")),
    path("elements/", include("elements.urls")),
    path("blog/", include("blog.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("user_management.urls")),
    path("accounts/", include("allauth.urls")),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()
urlpatterns += [path('captcha/', include('captcha.urls')),]

contact/models.py
from django.db import models


class Submitted(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(blank=True, null=True)
    subject = models.CharField(max_length=60)
    message = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return f"{self.name}: {self.subject}"

contact/forms.py
from django.forms import ModelForm
from contact.models import Submitted
from captcha.fields import CaptchaField


class ContactForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Submitted
        fields = "__all__"

about/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse


def main_about_page(request):
    return render(request, "travelista/about.html")

contact/views.py
from django.shortcuts import render
from contact.forms import ContactForm
from django.contrib import messages


def contact_main_page(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            set_name_form = form.save(commit=False)
            set_name_form.name = "anonymous"
            messages.add_message(request, messages.SUCCESS, "request saved")
            set_name_form.save()
        else:
            messages.add_message(request, messages.ERROR,
                                 "request didn't saved")
    else:
        form = ContactForm()
    context = {"form": form}
    return render(request, "travelista/contact.html", context)

templates/resume/about.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<!--================ Start Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>About Us</h2>
                <div class="page_link">
                    <a href="{% url 'home:index' %}">Home</a>
                    <a href="{% url 'home:about' %}">About</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ End Banner Area =================-->

<!--================ Start About Us Area =================-->
<section class="about_area section_gap">
    <div class="container">
        <div class="row justify-content-start align-items-center">
            <div class="col-lg-5">
                <div class="about_img">
                    <img class="" src="img/about-us.png" alt="">
                </div>
            </div>

            <div class="offset-lg-1 col-lg-5">
                <div class="main_title text-left">
                    <h2>let’s <br>
                        Introduce about <br>
                        myself</h2>
                    <p>
                        I started to learn programming since I was 12 , I learned python and a few years later
                        I begun to learn it's popular frameworks specially web frameworks such as django , flask ect...
                    </p>
                    <a class="primary_btn" href="#"><span>Download CV</span></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ End About Us Area =================-->




<!--================ Start Newsletter Area =================-->
<section class="newsletter_area">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-12">
                <div class="subscription_box text-center">
                    <h2 class="text-uppercase text-white">get update from anywhere</h2>
                    <p class="text-white">
                        Bearing Void gathering light light his eavening unto dont afraid.
                    </p>
                    <div class="subcribe-form" id="mc_embed_signup">
                        <form target="_blank" novalidate="true"
                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                            method="get" class="subscription relative">
                            <input name="EMAIL" placeholder="Email address" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Email address'" required="" type="email">
                            <div style="position: absolute; left: -5000px;">
                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                            </div>
                            <button class="primary-btn hover d-inline">Get Started</button>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ End Newsletter Area =================-->

{% endblock %}

templates/resume/contact.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<!--================ Start Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content text-center">
                <h2>Contact Us</h2>
                <div class="page_link">
                    <a href="{% url 'home:index' %}">Home</a>
                    <a href="{% url 'home:contact' %}">Contact</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ End Banner Area =================-->

<!--================Contact Area =================-->
<section class="contact_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="contact_info">
                    <div class="info_item">
                        <i class="lnr lnr-home"></i>
                        <h6>{{loc}}</h6>
                        <p>jordan St.</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-phone-handset"></i>
                        <h6><a href="#">{{phone}}</a></h6>
                        <p>Mon to Fri 9am to 6 pm</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope"></i>
                        <h6><a href="#">{{email}}</a></h6>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <form class="row contact_form" action="contact_process.php" method="post" id="contactForm"
                    novalidate="novalidate">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email"
                                placeholder="Enter email address">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" name="subject"
                                placeholder="Enter Subject">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control" name="message" id="message" rows="1"
                                placeholder="Enter Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="primary_btn">
                            <span>Send Message</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div id="mapBox" class="mapBox" data-lat="40.701083" data-lon="-74.1522848" data-zoom="13"
            data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia." data-mlat="40.701083"
            data-mlon="-74.1522848">
        </div>
    </div>
</section>
<!--================Contact Area =================-->

{% endblock %}

templates/resume/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<!--================ Start Home Banner Area =================-->
<section class="home_banner_area">
	<div class="banner_inner">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="banner_content">
						<h3 class="text-uppercase">Hell0</h3>
						<h1 class="text-uppercase">I am {{name}} {{last_name}}</h1>
						<h5 class="text-uppercase">senior {{WF}} developer</h5>
						<div class="d-flex align-items-center">
							<a class="primary_btn" href="#"><span>Hire Me</span></a>
							<a class="primary_btn tr-bg" href="#"><span>Get CV</span></a>
						</div>
					</div>
				</div>
				<div class="col-lg-5">
					<div class="home_right_img">
						<img class="" src="{% static 'img/banner/home-right.png' %}" alt="">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================ End Home Banner Area =================-->

<!--================ Start About Us Area =================-->
<section class="about_area section_gap">
	<div class="container">
		<div class="row justify-content-start align-items-center">
			<div class="col-lg-5">
				<div class="about_img">
					<img class="" src="{% static 'img/about-us.png' %}" alt="">
				</div>
			</div>

			<div class="offset-lg-1 col-lg-5">
				<div class="main_title text-left">
					<h2>let’s <br>
						Introduce about <br>
						myself</h2>
					<p>
						I started to learn programming since I was 12 , I learned python and a few years later
						I begun to learn it's popular frameworks specially web frameworks such as django , flask ect...

					</p>
					<a class="primary_btn" href="#"><span>Download CV</span></a>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================ End About Us Area =================-->

<!--================ Srart Brand Area =================-->
<section class="brand_area section_gap_bottom">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6">
				<div class="row">
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo1.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo2.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo3.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo4.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo5.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo6.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo7.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo8.png' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="single-brand-item d-table">
							<div class="d-table-cell text-center">
								<img src="{% static 'img/brands/logo9.png' %}" alt="">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="offset-lg-2 col-lg-4 col-md-6">
				<div class="client-info">
					<div class="d-flex mb-50">
						<span class="lage">6</span>
						<span class="smll">Years Experience Working</span>
					</div>
					<div class="call-now d-flex">
						<div>
							<span class="fa fa-phone"></span>
						</div>
						<div class="ml-15">
							<p>call me now</p>
							<h3>(+98)-933-881-3757</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================ End Brand Area =================-->

<!--================ Start Features Area =================-->
<section class="features_area">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-8 text-center">
				<div class="main_title">
					<h2>service offers </h2>
					<p>
						Is give may shall likeness made yielding spirit a itself togeth created
						after sea <br> is in beast beginning signs open god you're gathering ithe
					</p>
				</div>
			</div>
		</div>
		<div class="row feature_inner">
			<div class="col-lg-3 col-md-6">
				<div class="feature_item">
					<img src="{% static 'img/services/s1.png' %}" alt="">
					<h4>backend developing</h4>
					<p>Creeping for female light years that lesser can't evening heaven isn't bearing tree</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="feature_item">
					<img src="{% static 'img/services/s2.png' %}" alt="">
					<h4>deep learning (keras)</h4>
					<p>Creeping for female light years that lesser can't evening heaven isn't bearing tree</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="feature_item">
					<img src="{% static 'img/services/s3.png' %}" alt="">
					<h4>docker</h4>
					<p>Creeping for female light years that lesser can't evening heaven isn't bearing tree</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="feature_item">
					<img src="{% static 'img/services/s4.png' %}" alt="">
					<h4>seo optimize</h4>
					<p>Creeping for female light years that lesser can't evening heaven isn't bearing tree</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================ End Features Area =================-->

<!--================ Start Newsletter Area =================-->
<section class="newsletter_area">
	<div class="container">
		<div class="row justify-content-center align-items-center">
			<div class="col-lg-12">
				<div class="subscription_box text-center">
					<h2 class="text-uppercase text-white">get update from anywhere</h2>
					<p class="text-white">
						Bearing Void gathering light light his eavening unto dont afraid.
					</p>
					<div class="subcribe-form" id="mc_embed_signup">
						<form target="_blank" novalidate="true"
							action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							method="get" class="subscription relative">
							<input name="EMAIL" placeholder="Email address" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Email address'" required="" type="email">
							<div style="position: absolute; left: -5000px;">
								<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
							</div>
							<button class="primary-btn hover d-inline">Get Started</button>
							<div class="info"></div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================ End Newsletter Area =================-->


{% endblock %}