blog/urls.py
from django.urls import path, include
from blog.views import single_view, home_view, search_view
from blog.feeds import LatestBlogs

app_name = "blog"

urlpatterns = [
    path("", home_view, name="home"),
    path("post-<slug:slug>-<int:post_id>", single_view, name="single"),
    path("categories/<str:category_type>", home_view, name="categories"),
    path("tags/<str:tag_name>", home_view, name="tags"),
    path("categories/", home_view),
    path("writer/<str:author_username>", home_view, name="author"),
    path("rss/feed/", LatestBlogs()),
    path("search/", search_view, name="search")
    # path("name/<str:name>/email/<str:email>/year/<int:year>", test_view, name="test"),
    # path("post-<slug:slug>-<int:post_id>", post_view, name="details")
]

home/urls.py
from django.urls import path, include
from home.views import home_view, about_view, contact_view

app_name = "home"

urlpatterns = [
    path("", home_view, name="index"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact")
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import HomeStaticViewSitemap
from contact.sitemaps import ContactStaticViewSitemap
from about.sitemaps import AboutStaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {"home": HomeStaticViewSitemap,
            "contact": ContactStaticViewSitemap,
            "about": AboutStaticViewSitemap,
            "blog": BlogSitemap}

from robots.views import R


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("website/", include("website.urls"), name="web"),
    path("about/", include("about.urls")),
    path("contact/", include("contact.urls")),
    path("elements/", include("elements.urls")),
    path("blog/", include("blog.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("user_management.urls")),
    path("accounts/", include("allauth.urls")),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()
urlpatterns += [path('captcha/', include('captcha.urls')),]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    category_type = models.CharField(max_length=100)

    def __str__(self):
        return self.category_type


class Post(models.Model):
    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    tag = TaggableManager()
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=255)
    content = models.TextField()
    status = models.BooleanField(default=False)
    counted_views = models.IntegerField(default=0)
    published_date = models.DateTimeField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)
    login_require = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["-created_time"]
        # verbose_name = "پست"
        # verbose_name_plural = "پست ها 🗿👍"

    def __str__(self):
        return f"{self.id}, {self.title}"

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"slug": self.slug, "post_id": self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)
    email = models.EmailField()
    comment_content = models.TextField()
    image = models.ImageField(upload_to="blog/", default="blog/dog.jpg")
    approved = models.BooleanField(default=False)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_time"]

    def __str__(self):
        return self.name

blog/forms.py
from django.forms import ModelForm
from blog.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "subject", "comment_content"]

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from blog.models import Post, Comment
from blog.forms import CommentForm
from django.db.models import F, Max, Q
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.urls import reverse


def get_prev_next(post_id: int):
    prev_post = None
    next_post = None
    max_id = Post.objects.aggregate(Max("id"))["id__max"]
    for prev in range(post_id-1, 0, -1):
        if Post.objects.filter(id=prev, status=1).exists():
            prev_post = get_object_or_404(Post, pk=prev, status=1)
            break
    for the_next in range(post_id+1, max_id+1):
        if Post.objects.filter(id=the_next, status=1).exists():
            next_post = get_object_or_404(Post, pk=the_next, status=1)
            break

    return prev_post, next_post


def handle_login(request, post, post_id, slug):
    prev_p, next_p = get_prev_next(post_id)
    Post.objects.filter(id=post_id, slug=slug).update(
        counted_views=F("counted_views") + 1)
    comments = Comment.objects.filter(post=post.id, approved=1)
    # posts = Post.objects.filter(status=1)
    # post = get_object_or_404(posts, pk=post_id) ==> second way for the top code
    context = {"post": post, "next": next_p,
               "prev": prev_p, "comments": comments}
    return render(request, "travelista/blog/blog-single.html", context)


def single_view(request, slug, post_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            clean_data = form.save(commit=False)
            clean_data.post = Post.objects.get(id=post_id)
            clean_data.save()
            messages.add_message(
                request, messages.SUCCESS, "your comment added successfully")
        else:
            messages.add_message(
                request, messages.ERROR, "something went wrong when trying to post your comment")
    else:
        form = CommentForm()
    post = get_object_or_404(Post, pk=post_id, status=1)
    if not post.login_require:
        return handle_login(request, post, post_id, slug)
    elif request.user.is_authenticated:
        return handle_login(request, post, post_id, slug)
    else:
        messages.add_message(request, messages.INFO,
                             "you need to login to see this post")
        return HttpResponseRedirect(reverse("user:login"))


def home_view(request, **kwargs):
    Post.objects.filter(
        published_date__lte=timezone.now()).update(status=1)
    published_posts = Post.objects.filter(status=1)
    if kwargs.get("category_type"):
        published_posts = published_posts.filter(
            category__category_type=kwargs["category_type"])
    if kwargs.get("author_username"):
        published_posts = published_posts.filter(
            author__username=kwargs["author_username"])

    if kwargs.get("tag_name"):
        published_posts = published_posts.filter(
            tag__name__in=[kwargs["tag_name"]])

    paged_published_posts = Paginator(published_posts, 3)
    try:
        page_number = request.GET.get("page-num")
        paged_published_posts = paged_published_posts.get_page(page_number)

    except PageNotAnInteger:
        paged_published_posts = paged_published_posts.get_page(1)

    except EmptyPage:
        paged_published_posts = paged_published_posts.get_page(1)

    published_posts_dict = {"paged_published_posts": paged_published_posts}
    return render(request, "travelista/blog/blog-home.html", published_posts_dict)


# def test_view(request, name, email, year):
#     name_dict = {"name": name, "email": email, "year": year}
#     return render(request, "travelista/blog/test.html", name_dict)


# def test(request):
#     return render(request, "travelista/blog/test.html")


# def post_view(request, slug, post_id):
#     # post = Post.objects.get(id=pid)
#     post = get_object_or_404(Post, pk=post_id)
#     Post.objects.filter(id=post_id, slug=slug).update(
#         counted_views=F("counted_views") + 1)
#     post.refresh_from_db()
#     context = {"post": post}
#     return render(request, "travelista/blog/id.html", context)

def search_view(request):
    posts = Post.objects.filter(status=1)
    if request.method == "GET":
        if search_word := request.GET.get("search-element"):
            posts = posts.filter(
                Q(content__contains=search_word) | Q(title__contains=search_word))
    paged_published_posts = Paginator(posts, 3)
    try:
        page_num = request.GET.get("page-num")
        paged_published_posts = paged_published_posts.get_page(page_num)
    except PageNotAnInteger:
        paged_published_posts = paged_published_posts.get_page(1)
    except EmptyPage:
        paged_published_posts = paged_published_posts.get_page(1)

    qs = request.GET.copy()
    if "page-num" in qs:
        qs.pop("page-num")
    querystring = qs.urlencode()

    context = {"paged_published_posts": paged_published_posts,
               "querystring": querystring}
    return render(request, "travelista/blog/blog-home.html", context)

templates/travelista/blog/blog-home.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block container %}

<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope
				</h1>
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>
				<a href="blog-single.html" class="primary-btn">View More</a>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Social life</h4>
								<span></span>
								<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Politics</h4>
								<span></span>
								<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto"
									src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
								<h4 class="content-title mx-auto text-uppercase">Food</h4>
								<span></span>
								<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in paged_published_posts %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							{% if forloop.last %}
							<li><a href="{% url 'blog:categories' cat.category_type %}">{{cat.category_type}}</a></li>
							{% else %}
							<li><a href="{% url 'blog:categories' cat.category_type %}">{{cat.category_type}}</a></li>
							,
							{% endif %}
							{% endfor %}
						</ul>
						<!--because of the magic method (__str__) for first name {{post.author}} will print the username field of the user-->
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a
									href="{% url 'blog:author' post.author %}">{{post.author.get_full_name}}</a>
								<span class="lnr lnr-user"></span>
							</p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|naturaltime}}
								</a> <span class="lnr lnr-calendar-full"></span></p>
							<!--<p>{{12000000|intword}}</p> -->
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}}</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% get_comment_number post.id%}
									comments</a> <span class="lnr lnr-bubble"></span></p>
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:single' post.slug post.id %}">
							<h3>{{post.title}}</h3>
						</a>
						<p class="excert">
							{{post.content|truncatewords:5|safe}}
						</p>
						<a href="{% url 'blog:single' slug=post.slug post_id=post.id %}" class="primary-btn">View
							More</a>
					</div>
				</div>
				{% endfor %}
				<nav class="blog-pagination justify-content-center d-flex">
					<ul class="pagination">
						<li class="page-item">
							{% if paged_published_posts.has_previous %}
							{% if querystring %}
							<a href="?{{ querystring }}&page-num={{ paged_published_posts.previous_page_number }}"
								class="page-link" aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
							{% else %}
							<a href="?page-num={{ paged_published_posts.previous_page_number }}" class="page-link"
								aria-label="Previous">
								<span aria-hidden="true">
									<span class="lnr lnr-chevron-left"></span>
								</span>
							</a>
							{% endif %}
							{% endif %}
						</li>
						{% for page in paged_published_posts.paginator.page_range %}

						{% if page == paged_published_posts.number %}
						{% if querystring %}
						<li class="page-item active"><a href="?{{ querystring }}&page-num={{ page }}"
								class="page-link">{{page}}</a>
						</li>
						{% else %}
						<li class="page-item active"><a href="?page-num={{ page }}" class="page-link">{{page}}</a>
						</li>
						{% endif %}
						{% else %}
						{% if querystring %}
						<li class="page-item"><a href="?{{ querystring }}&page-num={{ page }}"
								class="page-link">{{page}}</a></li>
						{% else %}
						<li class="page-item"><a href="?page-num={{ page }}" class="page-link">{{page}}</a></li>
						{% endif %}
						{% endif %}
						{% endfor %}

						{% if paged_published_posts.has_next %}
						{% if querystring %}
						<a href="?{{ querystring }}&page-num={{ paged_published_posts.next_page_number }}"
							class="page-link" aria-label="Next">
							<span aria-hidden="true">
								<span class="lnr lnr-chevron-right"></span>
							</span>
						</a>
						{% else %}
						<a href="?page-num={{ paged_published_posts.next_page_number }}" class="page-link"
							aria-label="Next">
							<span aria-hidden="true">
								<span class="lnr lnr-chevron-right"></span>
							</span>
						</a>
						{% endif %}
						{% endif %}
						</li>
					</ul>
				</nav>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget search-widget">
						<form class="search-form" action="{% url 'blog:search' %}">
							<input placeholder="Search Posts" name="search-element" type="text"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>

					{% include 'travelista/blog/writer_info.html' %}


					{% latest_posts arg=4 %}


					<div class="single-sidebar-widget ads-widget">
						<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
					</div>

					{% get_categories %}


					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							{% for tag in paged_published_posts.tag.all %}
							<li>{{tag.name}}</li>
							{% endfor %}
						</ul>
					</div>

				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}

templates/travelista/blog/blog-single.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block container %}

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'home:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{%  url 'blog:home' %}">Blog <span
							class="lnr lnr-arrow-right"></span>{{post.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg' %}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							<li><a href="#">Food,</a></li>
							<li><a href="#">Technology,</a></li>
							<li><a href="#">Politics,</a></li>
							<li><a href="#">Lifestyle</a></li>
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">Mark wiens</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">12 Dec, 2017</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">1.2M Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments.count}} comments</a>
								<span class="lnr lnr-bubble"></span>
							</p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p>{{post.content|safe}}</p>
					</div>
					<div class="col-lg-12">
						<div class="row mt-30 mb-30">
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="">
							</div>
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="">
							</div>
						</div>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						{% if prev %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="{% url 'blog:single' slug=prev.slug post_id=prev.id %}"><img class="img-fluid"
										src="{% static 'img/blog/prev.jpg' %}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' slug=prev.slug post_id=prev.id %}"><span
										class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="{% url 'blog:single' slug=prev.slug post_id=prev.id %}">
									<h4>{{prev.title}}</h4>
								</a>
							</div>
						</div>
						{% else %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="detials">
								<p>nothing before</p>
								<h4>first published post</h4>
							</div>
						</div>
						{% endif %}
						{% if next %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="{% url 'blog:single' slug=next.slug post_id=next.id %}">
									<h4>{{next.title}}</h4>
								</a>
							</div>
							<div class="arrow">
								<a href=""><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="{% url 'blog:single' slug=next.slug post_id=next.id %}"><img class="img-fluid"
										src="{% static 'img/blog/next.jpg' %}" alt=""></a>
							</div>
						</div>
						{% else %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Last Post</p>
								<h4>last published post</h4>
							</div>
							<div class="arrow" style="opacity: 0;">
								<span class="lnr lnr-arrow-right"></span>
							</div>
							<div class="thumb" style="opacity: 0;">
								<img class="img-fluid" src="/static/img/blog/next.jpg" alt="">
							</div>
						</div>

						{% endif %}
					</div>

					<!-- <div class="comments-area">
						<div id="disqus_thread"></div>
						<script>
							/**
							*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
							*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
							/*
							var disqus_config = function () {
							this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
							this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
							};
							*/
							(function () { // DON'T EDIT BELOW THIS LINE
								var d = document, s = d.createElement('script');
								s.src = 'https://127-0-0-1-8000-n5keptozb1.disqus.com/embed.js';
								s.setAttribute('data-timestamp', +new Date());
								(d.head || d.body).appendChild(s);
							})();
						</script>
						<noscript>Please enable JavaScript to view the <a
								href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

					</div> -->
				</div>

				<div class="comments-area">
					{% if comments %}
					<!--first way: {{comments|length}}-->
					<!-- or: <h4>{% get_comment_number post.id %} comments</h4>-->
					<h4>{{comments.count}} comments</h4>
					{% for comment in comments %}
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{{comment.image.url}}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{comment.name}}</a></h5>
									<p class="date">{{comment.updated_time|naturaltime}}</p>
									<p class="comment">
										{{comment.comment_content}}
									</p>
								</div>
							</div>
							<!-- <div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div> -->
						</div>
					</div>
					{% endfor %}
					{% else %}
					<h4>no comments here</h4>
					{% endif %}

				</div>

				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form method="post" action="{% url 'blog:single' post.slug post.id %}">
						{% csrf_token %}
						<!-- you can use the input type=hidden and value=post_id for this part-->
						<div class="form-group form-inline">
							{% if request.user.is_authenticated %}
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" value="{{request.user.username}}"
									placeholder="Enter Name" onfocus="this.placeholder = ''"
									onblur="this.placeholder = 'Enter Name'" readonly>
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" value="{{request.user.email}}"
									placeholder="Enter email address" onfocus="this.placeholder = ''"
									onblur="this.placeholder = 'Enter email address'" readonly>
							</div>
							{% else %}
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
							{% endif %}

						</div>
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="comment_content" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>
						</div>
						<button type="submit" class="primary-btn text-uppercase">Post Comment
						</button>
					</form>
				</div>


			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget search-widget">
						<form class="search-form" action="#">
							<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Search Posts'">
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>


					{% include 'travelista/blog/writer_info.html' %}

					{% latest_posts arg=4 %}


					{% get_categories %}



					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							{% for tag in post.tag.all %}
							<li><a href="{% url 'blog:tags' tag.slug %}">{{tag.name}}</a></li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}

templates/travelista/blog/latest_posts.html
{% load static %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:single' slug=post.slug post_id=post.id %}">
                    <h6>{{post.title}}</h6>
                </a>
                <p>{{post.published_date|date:"D M Y"}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- {{published_posts}} -->