about/urls.py
from django.urls import path, include
from about.views import main_about_page

app_name = "about"

urlpatterns = [
    path("", main_about_page, name="about"),
]

blog/urls.py
from django.urls import path, include
from blog.views import single_view, home_view, search_view
from blog.feeds import LatestBlogs

app_name = "blog"

urlpatterns = [
    path("", home_view, name="home"),
    path("post-<slug:slug>-<int:post_id>", single_view, name="single"),
    path("categories/<str:category_type>", home_view, name="categories"),
    path("tags/<str:tag_name>", home_view, name="tags"),
    path("categories/", home_view),
    path("writer/<str:author_username>", home_view, name="author"),
    path("rss/feed/", LatestBlogs()),
    path("search/", search_view, name="search")
    # path("name/<str:name>/email/<str:email>/year/<int:year>", test_view, name="test"),
    # path("post-<slug:slug>-<int:post_id>", post_view, name="details")
]

contact/urls.py
from django.contrib import admin
from django.urls import path, include
from contact.views import contact_main_page

app_name = "contact"


urlpatterns = [
    path("", contact_main_page, name="contact"),
]

elements/urls.py
from django.contrib import admin
from django.urls import path, include
from elements.views import elements_main_page

app_name = "elements"


urlpatterns = [
    path("", elements_main_page, name="elements"),
]

home/urls.py
from django.urls import path, include
from home.views import home_view, about_view, contact_view

app_name = "home"

urlpatterns = [
    path("", home_view, name="index"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact")
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import HomeStaticViewSitemap
from contact.sitemaps import ContactStaticViewSitemap
from about.sitemaps import AboutStaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {"home": HomeStaticViewSitemap,
            "contact": ContactStaticViewSitemap,
            "about": AboutStaticViewSitemap,
            "blog": BlogSitemap}

from robots.views import R


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("website/", include("website.urls"), name="web"),
    path("about/", include("about.urls")),
    path("contact/", include("contact.urls")),
    path("elements/", include("elements.urls")),
    path("blog/", include("blog.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    path("robots.txt", include("robots.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("user_management.urls")),
    path("accounts/", include("allauth.urls")),
    path('accounts/two-factor/', include('allauth_2fa.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()
urlpatterns += [path('captcha/', include('captcha.urls')),]

templates/base.html
{% load static %}
{% load compress %}



<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!-- CSS============================================= -->
    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/messages.css' %}">
    {% endcompress %}

    <link rel="canonical" href="https://arvin-behbahani.ir/">

</head>

<body>
    <header id="header">
        <div class="header-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                        <ul>
                            {% if request.user.is_authenticated %}
                            <li><a href="{% url 'user:account_profile' %}">you're logged in as
                                    {{request.user.username}}</a>
                            </li>
                            <li><a href="{% url 'account_logout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'user:account_login' %}">Login</a></li>
                            <li><a href="{% url 'user:account_signup' %}">Signup</a></li>
                            {% endif %}
                            <li><a href="#">Buy Tickets</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                        <div class="header-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="{% url 'home:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="{% url 'home:index' %}">Home</a></li>
                        <li><a href="{% url 'about:about' %}">About</a></li>
                        <li><a href="{% url 'blog:home' %}">Blog</a>

                        </li>
                        <li class="menu-has-children"><a href="">Pages</a>
                            <ul>
                                <li><a href="{% url 'elements:elements' %}">Elements</a></li>
                                <li class="menu-has-children"><a href="">Level 2 </a>
                                    <ul>
                                        <li><a href="#">Item One</a></li>
                                        <li><a href="#">Item Two</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header>




    {% block container %}

    {% endblock container %}


    {% if messages %}
    <div id="toast-container">
        {% for message in messages %}
        <div class="toast show toast-{{ message.tags }}">
            <span>{{ message }}</span>
            <button class="close-btn" onclick="closeToast(this)">×</button>
        </div>
        {% endfor %}
    </div>
    {% endif %}






    <footer class="footer-area section-gap">
        <div class="container">

            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Agency</h6>
                        <p>
                            The world has become so fast paced that people don’t want to stand by reading a page of
                            information, they would much rather look at a presentation and understand the message.
                            It
                            has come to a point
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Navigation Links</h6>
                        <div class="row">
                            <div class="col">
                                <ul>
                                    <li><a href="#">Home</a></li>
                                    <li><a href="#">Feature</a></li>
                                    <li><a href="#">Services</a></li>
                                    <li><a href="#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col">
                                <ul>
                                    <li><a href="#">Team</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>
                            For business professionals caught between high OEM price and mediocre print and graphic
                            output.
                        </p>
                        <div>
                            <form action=" {% url 'home:index' %}" method="post" class="subscription relative">
                                {% csrf_token %}
                                <div class="input-group d-flex flex-row">
                                    <input name="email" placeholder="Email Address" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn bb-btn" type="submit"><span
                                            class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">InstaFeed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                            <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-sm-12 footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template
                    is
                    made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>


    {% compress js %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <!--    <script
        src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA' %}"></script> -->
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/show_message.js' %}"></script>
    {% endcompress %}







</body>

</html>